name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-images:
    strategy:
      max-parallel: 5
      matrix:
        coredns-version:
          - "1.11.3"
        go-version:
          - "1.23.2"
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get variables
        id: vars
        run: |
          echo "timestamp=$(TZ=':America/Los_Angeles' date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "repo=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            GO_VERSION=${{ matrix.go-version }}
            COREDNS_VERSION=${{ matrix.coredns-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ steps.vars.outputs.repo }}/coredns-blocker-${{ matrix.coredns-version }}:latest
            ghcr.io/${{ steps.vars.outputs.repo }}/coredns-blocker-${{ matrix.coredns-version }}:${{ steps.vars.outputs.timestamp }}
